version: '3.7'

services:
    # Development related
    test-sqlite:
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        env_file: environment2.env
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: pytest
        volumes:
            - ./OperatorsBackend:/opt/code

    test-postgresql:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: pytest
        depends_on:
            - db
            - rabbitmq
        volumes:
            - ./OperatorsBackend:/opt/code

    # Pipeline actions
    test:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: pytest
        depends_on:
            - db
            - rabbitmq

    static-analysis:
        build:
            dockerfile: docker/app/Dockerfile
            context: .
        entrypoint: flake8

    db:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
            args:
                # These values should be in sync with environment
                # for development. If you change them, you'll
                # need to rebuild the container
                - POSTGRES_DB=operator
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=somepassword
                - POSTGRES_PORT=5432
            

    # Producion related
    # Note that db-debug is the same as db, but it exposes locally
    # port 5432 to access PostgreSQL
    db-debug:
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
            args:
                # These values should be in sync with environment
                # for development. If you change them, you'll
                # need to rebuild the container
                - POSTGRES_DB=operator
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=somepassword
                - POSTGRES_PORT=5432
        ports:
            - "5432:5432"

    server: &server
        env_file: environment.env
        image: operators_server
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "7001:8000"
        depends_on:
            - db
            - rabbitmq
            - celery_worker

    # Rabbit message queue
    rabbitmq:
        image: rabbitmq:3.8-alpine

    # Celery Worker
    celery_worker:
        env_file: environment.env
        image: celery_terminal
        build:
            context: .
            dockerfile: docker/celery/Dockerfile
        ports: []
        depends_on: 
            - rabbitmq
            - db